source "https://rubygems.org"

ruby "3.1.4"

gem "rails", "~> 7.1.5"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "bcrypt", "~> 3.1.7"
gem "tzinfo-data", platforms: %i[ mswin jruby ]
gem "bootsnap", require: false